[tool.poetry]
name = "fastapi-mcp-server"
version = "0.1.0"
description = "統計分析與機器學習推論的 MCP Server"
authors = ["Your Name <your.email@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"